
apiVersion: v1
kind: Namespace
metadata:
  name: test-egress

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-egress
  labels:
    app: test-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-to-external
  namespace: test-egress
spec:
  endpointSelector:
    matchLabels:
      app: test-pod
  egress:
  - toCIDR:
    - 8.8.8.8/32
